version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/carlpett/terraform-provider-sops
    steps:
      - checkout
      - run: gpg --import test/testing-key.pgp
      - run: make test build
      - store_artifacts:
          path: terraform-provider-sops
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/carlpett/terraform-provider-sops
    steps:
      - checkout
      - run: gpg --import test/testing-key.pgp
      - run: make test build
      - run:
          name: Download github-release tool
          command: |
            curl -sL 'https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2' | \
              tar xjf - --strip-components 3 -C /go/bin
      - run: github-release upload --user carlpett --repo terraform-provider-sops --tag $CIRCLE_TAG --name terraform-provider-sops_$CIRCLE_TAG-linux-amd64 --file terraform-provider-sops
      - run:
          name: Trigger Docker Hub automated build
          command: |
            curl -X POST -H "Content-Type: application/json" \
              --data "{\"source_type\": \"Tag\", \"source_name\": \"$CIRCLE_TAG\"}" \
              https://registry.hub.docker.com/u/carlpett/terraform-provider-sops/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
      - store_artifacts:
          path: terraform-provider-sops

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
