name: Release

on:
  push:
    tags:
      - v*

env:
  GO_VERSION: '1.18'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .

      - name: Import test GPG key
        run: gpg --import test/testing-key.pgp

      - name: Test
        run: make test

      - name: Crossbuild
        run: make crossbuild

      - name: Release
        run: make release

      - name: Trigger Docker Hub automated build
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --data '{"source_type": "Tag", "source_name": "${{ github.ref_name }}"}' \
            "https://registry.hub.docker.com/u/carlpett/terraform-provider-sops/trigger/${{ secrets.DOCKER_HUB_TRIGGER_TOKEN }}/"
